### ISSUE TITLE
Hugo's taxonomy and deprecated function warnings to fix

### ISSUE THREAD

**Issue by areee** [schmanat/hugo-highlights-theme#18]
When running `hugo server` and `hugo` commands, the bash terminal gives me these warnings: 
- ``
WARN 2020/03/30 19:39:00 found no layout file for "HTML" for kind "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
``
- ``
WARN 2020/03/30 19:39:00 Page.Hugo is deprecated and will be removed in a future release. Use the global hugo function.
``

Could they be fixed? I suppose that particularly the second warning is quite important one.

**Comment by schmanat** [comment]
Hi @areee 

thx for your hint, i have fixed the deprecated warning. If I find the time i will also fix the first warning.
