### ISSUE TITLE
fab fonts not displayed in skill section

### ISSUE THREAD

**Issue by desixma** [schmanat/hugo-highlights-theme#19]
Hi, thanks for your nice theme!
I just added a brand icon,  icon = "fa-linkedin", code "\f08c", but it won't get displayed. I checked in font-awesome.min.css, the icon is there and the code content info is generated properly when I inspect the page. So I assume it has something to do with the font weight of the brand icons? Unfortunately, I am not so well-versed in css/sass, so I couldn't follow that trail further.

**Comment by desixma** [comment]
one more interesting effect - the social icons at the bottom of the page are displayed correctly, when in local debug mode but not on the server. Teh same codes entered in the skills section do not work at all.

**Comment by desixma** [comment]
ok the bad guy seems to be the css class in layout/partials/List.html:

`<span class="icon major fas {{ .icon }}"></span>`

doesn't work for brand icons. Surely, there is a way to resolve that elegantly within css/sass. For me, it was sufficient to change the line to 

`<span class="icon major {{.icontype}} {{ .icon }}"></span>`

which allows me to set the icontype "fas" or "fab" as needed from within config.toml.

**Comment by schmanat** [comment]
Thanks for your issue, should be fix with https://github.com/schmanat/hugo-highlights-theme/commit/ba743673042dd82db95b262adf158476abd68439
