### ISSUE TITLE
buttonText params not called by partials

### ISSUE THREAD

**Issue by stevensonmt** [schmanat/hugo-highlights-theme#3]
For whatever reason the param buttonText was not acceptable.  No text was showing up and on inspection the `<a href ...></a>` were just like that -- no text called by the partials.  Changing the param name to "button" fixed the issue.  Is buttonText reserved by something?  Seems the camelcase might have been the issue on further review.

**Comment by schmanat** [comment]
hi, thx for reporting this issue.

You're right it seems that camelcase is the problem. 
You are using the latest version of Hugo? 
With version 0.15 it works (with camelcase).

**Comment by stevensonmt** [comment]
my Hugo version is 0.17-1.

Thanks for the great theme, btw.

**Comment by schmanat** [comment]
I found only hugo v 0.17 and thested it, and it works. Can you tell me how i can get the version 0.17-1?

Again: With version 0.16 and 0.17 it works.

**Comment by stevensonmt** [comment]
hmm.  I installed via arch linux AUR hugo package https://aur.archlinux.org/packages/hugo/

**Comment by schmanat** [comment]
hmm, strange. I use Hugo with Windows. 

OK, to prevent this issue i converted camelCase params to lowercase. So i hope theres no problem anymore.
