### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by sandys** [schmanat/hugo-highlights-theme#4]
hi,
im on chrome with 16 gb ram and core i7

the site slows down completely when im scrolling. i think its because of the background animation.

is it possible to get rid of the animation and have a fixed image?

**Comment by schmanat** [comment]
oha ...
thanks for your issue, i added a flag to enable "backgrounds per section" or disable it. in the config.toml exists now the param **backgroundpersection**, set it to false and you have one "normal" background image.
