### ISSUE TITLE
About & Skills should use image set in config.toml

### ISSUE THREAD

**Issue by sampettitdesigns** [schmanat/hugo-highlights-theme#7]
Noticed the About and Skills sections were ignoring the background image set in the theme's config.toml for them to use but were instead all using that set for the Info section. Have submitted a pull request adjusting the About.html and skills.html partials to correctly use the background images set in config.toml. Am new to GitHub so not sure the etiquette, hope this is helpful.

**Comment by schmanat** [comment]
thx for your PR I have merged it. https://github.com/schmanat/hugo-highlights-theme/commit/54a7feefe1aeb15dabcad2e3f18cacf02a888123
